#!/usr/bin/env node
// Regenerates src/version.ts from package.json so the CLI's --version
// output can never drift from the published package version. Run as
// prebuild — see packages/cli/package.json scripts.build.
//
// src/version.ts is gitignored; this script is the only writer.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const pkgPath = resolve(here, '..', 'package.json')
const outPath = resolve(here, '..', 'src', 'version.ts')

const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'))
const banner = '// Auto-generated by scripts/sync-version.mjs from package.json. Do not edit.\n'
const version = String(pkg.version).replaceAll('\\', '\\\\').replaceAll("'", "\\'")
writeFileSync(outPath, `${banner}export const VERSION = '${version}'\n`)
